### ISSUE TITLE
Interesting ideas - prettier + eslint

### ISSUE THREAD

**Issue by rafadorado** [jramcast/create-js-package#1]
Hi, thanks for this tool! :+1: 

Just sharing these articles that may be you consider interesting for code-linting.

https://medium.com/@netczuk/your-last-eslint-config-9e35bace2f99

https://medium.com/@netczuk/even-faster-code-formatting-using-eslint-22b80d061461

Cheers

**Comment by jramcast** [comment]
Sure! i'll take a look

**Comment by jramcast** [comment]
Included in v1.1.1 26c79e7e53022aeaea1c04e3460c488a40035407
